package com.can.minidoctor.core.dao.mapper;

import com.can.minidoctor.core.entity.MinidoctorDatement;
import com.can.minidoctor.core.entity.MinidoctorDatementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MinidoctorDatementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    int countByExample(MinidoctorDatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    int deleteByExample(MinidoctorDatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    int insert(MinidoctorDatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    int insertSelective(MinidoctorDatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    List<MinidoctorDatement> selectByExample(MinidoctorDatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    MinidoctorDatement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") MinidoctorDatement record, @Param("example") MinidoctorDatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    int updateByExample(@Param("record") MinidoctorDatement record, @Param("example") MinidoctorDatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    int updateByPrimaryKeySelective(MinidoctorDatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    int updateByPrimaryKey(MinidoctorDatement record);
}