package com.can.minidoctor.core.dao.mapper;

import com.can.minidoctor.core.entity.MinidoctorArrangement;
import com.can.minidoctor.core.entity.MinidoctorArrangementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MinidoctorArrangementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    int countByExample(MinidoctorArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    int deleteByExample(MinidoctorArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    int insert(MinidoctorArrangement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    int insertSelective(MinidoctorArrangement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    List<MinidoctorArrangement> selectByExample(MinidoctorArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    MinidoctorArrangement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") MinidoctorArrangement record, @Param("example") MinidoctorArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    int updateByExample(@Param("record") MinidoctorArrangement record, @Param("example") MinidoctorArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    int updateByPrimaryKeySelective(MinidoctorArrangement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    int updateByPrimaryKey(MinidoctorArrangement record);
}