package com.can.minidoctor.core.dao.mapper;

import com.can.minidoctor.core.entity.MinidoctorUser;
import com.can.minidoctor.core.entity.MinidoctorUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MinidoctorUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    int countByExample(MinidoctorUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    int deleteByExample(MinidoctorUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    int insert(MinidoctorUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    int insertSelective(MinidoctorUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    List<MinidoctorUser> selectByExample(MinidoctorUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    MinidoctorUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") MinidoctorUser record, @Param("example") MinidoctorUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    int updateByExample(@Param("record") MinidoctorUser record, @Param("example") MinidoctorUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    int updateByPrimaryKeySelective(MinidoctorUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    int updateByPrimaryKey(MinidoctorUser record);
}