package com.can.minidoctor.core.dao.mapper;

import com.can.minidoctor.core.entity.MiniUsers;
import com.can.minidoctor.core.entity.MiniUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MiniUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    int countByExample(MiniUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    int deleteByExample(MiniUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    int insert(MiniUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    int insertSelective(MiniUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    List<MiniUsers> selectByExample(MiniUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    MiniUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") MiniUsers record, @Param("example") MiniUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    int updateByExample(@Param("record") MiniUsers record, @Param("example") MiniUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    int updateByPrimaryKeySelective(MiniUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    int updateByPrimaryKey(MiniUsers record);
}