spring:
    profiles:
      active: "@activatedProperties@"
wx:
  miniprogram:
    loginUrl: https://api.weixin.qq.com/sns/jscode2session?grant_type=authorization_code
    accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
    getWXACodeUnlimit: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=
    sendWxTemplateNotice: https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token=