package com.can.minidoctor.core.entity;

import java.io.Serializable;
import java.util.Date;

public class MinidoctorArrangement implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_arrangement.id
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_arrangement.work_date
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private Date workDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_arrangement.work_date_str
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private String workDateStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_arrangement.before_noon
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private Byte beforeNoon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_arrangement.after_noon
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private Byte afterNoon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_arrangement.before_supper
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private Byte beforeSupper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_arrangement.after_supper
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private Byte afterSupper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_arrangement.work_type
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private Byte workType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_arrangement.hostpital
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private Byte hostpital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_arrangement.create_time
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_arrangement.id
     *
     * @return the value of minidoctor_arrangement.id
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_arrangement.id
     *
     * @param id the value for minidoctor_arrangement.id
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_arrangement.work_date
     *
     * @return the value of minidoctor_arrangement.work_date
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Date getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_arrangement.work_date
     *
     * @param workDate the value for minidoctor_arrangement.work_date
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setWorkDate(Date workDate) {
        this.workDate = workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_arrangement.work_date_str
     *
     * @return the value of minidoctor_arrangement.work_date_str
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public String getWorkDateStr() {
        return workDateStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_arrangement.work_date_str
     *
     * @param workDateStr the value for minidoctor_arrangement.work_date_str
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setWorkDateStr(String workDateStr) {
        this.workDateStr = workDateStr == null ? null : workDateStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_arrangement.before_noon
     *
     * @return the value of minidoctor_arrangement.before_noon
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Byte getBeforeNoon() {
        return beforeNoon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_arrangement.before_noon
     *
     * @param beforeNoon the value for minidoctor_arrangement.before_noon
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setBeforeNoon(Byte beforeNoon) {
        this.beforeNoon = beforeNoon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_arrangement.after_noon
     *
     * @return the value of minidoctor_arrangement.after_noon
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Byte getAfterNoon() {
        return afterNoon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_arrangement.after_noon
     *
     * @param afterNoon the value for minidoctor_arrangement.after_noon
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setAfterNoon(Byte afterNoon) {
        this.afterNoon = afterNoon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_arrangement.before_supper
     *
     * @return the value of minidoctor_arrangement.before_supper
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Byte getBeforeSupper() {
        return beforeSupper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_arrangement.before_supper
     *
     * @param beforeSupper the value for minidoctor_arrangement.before_supper
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setBeforeSupper(Byte beforeSupper) {
        this.beforeSupper = beforeSupper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_arrangement.after_supper
     *
     * @return the value of minidoctor_arrangement.after_supper
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Byte getAfterSupper() {
        return afterSupper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_arrangement.after_supper
     *
     * @param afterSupper the value for minidoctor_arrangement.after_supper
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setAfterSupper(Byte afterSupper) {
        this.afterSupper = afterSupper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_arrangement.work_type
     *
     * @return the value of minidoctor_arrangement.work_type
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Byte getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_arrangement.work_type
     *
     * @param workType the value for minidoctor_arrangement.work_type
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setWorkType(Byte workType) {
        this.workType = workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_arrangement.hostpital
     *
     * @return the value of minidoctor_arrangement.hostpital
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Byte getHostpital() {
        return hostpital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_arrangement.hostpital
     *
     * @param hostpital the value for minidoctor_arrangement.hostpital
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setHostpital(Byte hostpital) {
        this.hostpital = hostpital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_arrangement.create_time
     *
     * @return the value of minidoctor_arrangement.create_time
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_arrangement.create_time
     *
     * @param createTime the value for minidoctor_arrangement.create_time
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}