package com.can.minidoctor.core.entity;

import java.io.Serializable;
import java.util.Date;

public class MinidoctorUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_user.id
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_user.open_id
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_user.nick_name
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_user.head_url
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    private String headUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_user.user_role
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    private Byte userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_user.gender
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_user.city
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_user.create_time
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_user.update_time
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table minidoctor_user
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_user.id
     *
     * @return the value of minidoctor_user.id
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_user.id
     *
     * @param id the value for minidoctor_user.id
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_user.open_id
     *
     * @return the value of minidoctor_user.open_id
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_user.open_id
     *
     * @param openId the value for minidoctor_user.open_id
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_user.nick_name
     *
     * @return the value of minidoctor_user.nick_name
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_user.nick_name
     *
     * @param nickName the value for minidoctor_user.nick_name
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_user.head_url
     *
     * @return the value of minidoctor_user.head_url
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_user.head_url
     *
     * @param headUrl the value for minidoctor_user.head_url
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_user.user_role
     *
     * @return the value of minidoctor_user.user_role
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public Byte getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_user.user_role
     *
     * @param userRole the value for minidoctor_user.user_role
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public void setUserRole(Byte userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_user.gender
     *
     * @return the value of minidoctor_user.gender
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_user.gender
     *
     * @param gender the value for minidoctor_user.gender
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_user.city
     *
     * @return the value of minidoctor_user.city
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_user.city
     *
     * @param city the value for minidoctor_user.city
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_user.create_time
     *
     * @return the value of minidoctor_user.create_time
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_user.create_time
     *
     * @param createTime the value for minidoctor_user.create_time
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_user.update_time
     *
     * @return the value of minidoctor_user.update_time
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_user.update_time
     *
     * @param updateTime the value for minidoctor_user.update_time
     *
     * @mbggenerated Sun Jan 13 13:57:33 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}