package com.can.minidoctor.core.entity;

import java.io.Serializable;
import java.util.Date;

public class MiniUsers implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mini_users.id
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mini_users.open_id
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mini_users.nick_name
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mini_users.head_pic
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    private String headPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mini_users.create_time
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mini_users
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mini_users.id
     *
     * @return the value of mini_users.id
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mini_users.id
     *
     * @param id the value for mini_users.id
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mini_users.open_id
     *
     * @return the value of mini_users.open_id
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mini_users.open_id
     *
     * @param openId the value for mini_users.open_id
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mini_users.nick_name
     *
     * @return the value of mini_users.nick_name
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mini_users.nick_name
     *
     * @param nickName the value for mini_users.nick_name
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mini_users.head_pic
     *
     * @return the value of mini_users.head_pic
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mini_users.head_pic
     *
     * @param headPic the value for mini_users.head_pic
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic == null ? null : headPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mini_users.create_time
     *
     * @return the value of mini_users.create_time
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mini_users.create_time
     *
     * @param createTime the value for mini_users.create_time
     *
     * @mbggenerated Mon Dec 17 21:48:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}