package com.can.minidoctor.core.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MinidoctorArrangementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public MinidoctorArrangementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWorkDateIsNull() {
            addCriterion("work_date is null");
            return (Criteria) this;
        }

        public Criteria andWorkDateIsNotNull() {
            addCriterion("work_date is not null");
            return (Criteria) this;
        }

        public Criteria andWorkDateEqualTo(Date value) {
            addCriterion("work_date =", value, "workDate");
            return (Criteria) this;
        }

        public Criteria andWorkDateNotEqualTo(Date value) {
            addCriterion("work_date <>", value, "workDate");
            return (Criteria) this;
        }

        public Criteria andWorkDateGreaterThan(Date value) {
            addCriterion("work_date >", value, "workDate");
            return (Criteria) this;
        }

        public Criteria andWorkDateGreaterThanOrEqualTo(Date value) {
            addCriterion("work_date >=", value, "workDate");
            return (Criteria) this;
        }

        public Criteria andWorkDateLessThan(Date value) {
            addCriterion("work_date <", value, "workDate");
            return (Criteria) this;
        }

        public Criteria andWorkDateLessThanOrEqualTo(Date value) {
            addCriterion("work_date <=", value, "workDate");
            return (Criteria) this;
        }

        public Criteria andWorkDateIn(List<Date> values) {
            addCriterion("work_date in", values, "workDate");
            return (Criteria) this;
        }

        public Criteria andWorkDateNotIn(List<Date> values) {
            addCriterion("work_date not in", values, "workDate");
            return (Criteria) this;
        }

        public Criteria andWorkDateBetween(Date value1, Date value2) {
            addCriterion("work_date between", value1, value2, "workDate");
            return (Criteria) this;
        }

        public Criteria andWorkDateNotBetween(Date value1, Date value2) {
            addCriterion("work_date not between", value1, value2, "workDate");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrIsNull() {
            addCriterion("work_date_str is null");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrIsNotNull() {
            addCriterion("work_date_str is not null");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrEqualTo(String value) {
            addCriterion("work_date_str =", value, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrNotEqualTo(String value) {
            addCriterion("work_date_str <>", value, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrGreaterThan(String value) {
            addCriterion("work_date_str >", value, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrGreaterThanOrEqualTo(String value) {
            addCriterion("work_date_str >=", value, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrLessThan(String value) {
            addCriterion("work_date_str <", value, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrLessThanOrEqualTo(String value) {
            addCriterion("work_date_str <=", value, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrLike(String value) {
            addCriterion("work_date_str like", value, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrNotLike(String value) {
            addCriterion("work_date_str not like", value, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrIn(List<String> values) {
            addCriterion("work_date_str in", values, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrNotIn(List<String> values) {
            addCriterion("work_date_str not in", values, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrBetween(String value1, String value2) {
            addCriterion("work_date_str between", value1, value2, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andWorkDateStrNotBetween(String value1, String value2) {
            addCriterion("work_date_str not between", value1, value2, "workDateStr");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonIsNull() {
            addCriterion("before_noon is null");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonIsNotNull() {
            addCriterion("before_noon is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonEqualTo(Byte value) {
            addCriterion("before_noon =", value, "beforeNoon");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonNotEqualTo(Byte value) {
            addCriterion("before_noon <>", value, "beforeNoon");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonGreaterThan(Byte value) {
            addCriterion("before_noon >", value, "beforeNoon");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonGreaterThanOrEqualTo(Byte value) {
            addCriterion("before_noon >=", value, "beforeNoon");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonLessThan(Byte value) {
            addCriterion("before_noon <", value, "beforeNoon");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonLessThanOrEqualTo(Byte value) {
            addCriterion("before_noon <=", value, "beforeNoon");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonIn(List<Byte> values) {
            addCriterion("before_noon in", values, "beforeNoon");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonNotIn(List<Byte> values) {
            addCriterion("before_noon not in", values, "beforeNoon");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonBetween(Byte value1, Byte value2) {
            addCriterion("before_noon between", value1, value2, "beforeNoon");
            return (Criteria) this;
        }

        public Criteria andBeforeNoonNotBetween(Byte value1, Byte value2) {
            addCriterion("before_noon not between", value1, value2, "beforeNoon");
            return (Criteria) this;
        }

        public Criteria andAfterNoonIsNull() {
            addCriterion("after_noon is null");
            return (Criteria) this;
        }

        public Criteria andAfterNoonIsNotNull() {
            addCriterion("after_noon is not null");
            return (Criteria) this;
        }

        public Criteria andAfterNoonEqualTo(Byte value) {
            addCriterion("after_noon =", value, "afterNoon");
            return (Criteria) this;
        }

        public Criteria andAfterNoonNotEqualTo(Byte value) {
            addCriterion("after_noon <>", value, "afterNoon");
            return (Criteria) this;
        }

        public Criteria andAfterNoonGreaterThan(Byte value) {
            addCriterion("after_noon >", value, "afterNoon");
            return (Criteria) this;
        }

        public Criteria andAfterNoonGreaterThanOrEqualTo(Byte value) {
            addCriterion("after_noon >=", value, "afterNoon");
            return (Criteria) this;
        }

        public Criteria andAfterNoonLessThan(Byte value) {
            addCriterion("after_noon <", value, "afterNoon");
            return (Criteria) this;
        }

        public Criteria andAfterNoonLessThanOrEqualTo(Byte value) {
            addCriterion("after_noon <=", value, "afterNoon");
            return (Criteria) this;
        }

        public Criteria andAfterNoonIn(List<Byte> values) {
            addCriterion("after_noon in", values, "afterNoon");
            return (Criteria) this;
        }

        public Criteria andAfterNoonNotIn(List<Byte> values) {
            addCriterion("after_noon not in", values, "afterNoon");
            return (Criteria) this;
        }

        public Criteria andAfterNoonBetween(Byte value1, Byte value2) {
            addCriterion("after_noon between", value1, value2, "afterNoon");
            return (Criteria) this;
        }

        public Criteria andAfterNoonNotBetween(Byte value1, Byte value2) {
            addCriterion("after_noon not between", value1, value2, "afterNoon");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperIsNull() {
            addCriterion("before_supper is null");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperIsNotNull() {
            addCriterion("before_supper is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperEqualTo(Byte value) {
            addCriterion("before_supper =", value, "beforeSupper");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperNotEqualTo(Byte value) {
            addCriterion("before_supper <>", value, "beforeSupper");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperGreaterThan(Byte value) {
            addCriterion("before_supper >", value, "beforeSupper");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperGreaterThanOrEqualTo(Byte value) {
            addCriterion("before_supper >=", value, "beforeSupper");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperLessThan(Byte value) {
            addCriterion("before_supper <", value, "beforeSupper");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperLessThanOrEqualTo(Byte value) {
            addCriterion("before_supper <=", value, "beforeSupper");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperIn(List<Byte> values) {
            addCriterion("before_supper in", values, "beforeSupper");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperNotIn(List<Byte> values) {
            addCriterion("before_supper not in", values, "beforeSupper");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperBetween(Byte value1, Byte value2) {
            addCriterion("before_supper between", value1, value2, "beforeSupper");
            return (Criteria) this;
        }

        public Criteria andBeforeSupperNotBetween(Byte value1, Byte value2) {
            addCriterion("before_supper not between", value1, value2, "beforeSupper");
            return (Criteria) this;
        }

        public Criteria andAfterSupperIsNull() {
            addCriterion("after_supper is null");
            return (Criteria) this;
        }

        public Criteria andAfterSupperIsNotNull() {
            addCriterion("after_supper is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSupperEqualTo(Byte value) {
            addCriterion("after_supper =", value, "afterSupper");
            return (Criteria) this;
        }

        public Criteria andAfterSupperNotEqualTo(Byte value) {
            addCriterion("after_supper <>", value, "afterSupper");
            return (Criteria) this;
        }

        public Criteria andAfterSupperGreaterThan(Byte value) {
            addCriterion("after_supper >", value, "afterSupper");
            return (Criteria) this;
        }

        public Criteria andAfterSupperGreaterThanOrEqualTo(Byte value) {
            addCriterion("after_supper >=", value, "afterSupper");
            return (Criteria) this;
        }

        public Criteria andAfterSupperLessThan(Byte value) {
            addCriterion("after_supper <", value, "afterSupper");
            return (Criteria) this;
        }

        public Criteria andAfterSupperLessThanOrEqualTo(Byte value) {
            addCriterion("after_supper <=", value, "afterSupper");
            return (Criteria) this;
        }

        public Criteria andAfterSupperIn(List<Byte> values) {
            addCriterion("after_supper in", values, "afterSupper");
            return (Criteria) this;
        }

        public Criteria andAfterSupperNotIn(List<Byte> values) {
            addCriterion("after_supper not in", values, "afterSupper");
            return (Criteria) this;
        }

        public Criteria andAfterSupperBetween(Byte value1, Byte value2) {
            addCriterion("after_supper between", value1, value2, "afterSupper");
            return (Criteria) this;
        }

        public Criteria andAfterSupperNotBetween(Byte value1, Byte value2) {
            addCriterion("after_supper not between", value1, value2, "afterSupper");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNull() {
            addCriterion("work_type is null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNotNull() {
            addCriterion("work_type is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeEqualTo(Byte value) {
            addCriterion("work_type =", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotEqualTo(Byte value) {
            addCriterion("work_type <>", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThan(Byte value) {
            addCriterion("work_type >", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("work_type >=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThan(Byte value) {
            addCriterion("work_type <", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThanOrEqualTo(Byte value) {
            addCriterion("work_type <=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIn(List<Byte> values) {
            addCriterion("work_type in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotIn(List<Byte> values) {
            addCriterion("work_type not in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeBetween(Byte value1, Byte value2) {
            addCriterion("work_type between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("work_type not between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andHostpitalIsNull() {
            addCriterion("hostpital is null");
            return (Criteria) this;
        }

        public Criteria andHostpitalIsNotNull() {
            addCriterion("hostpital is not null");
            return (Criteria) this;
        }

        public Criteria andHostpitalEqualTo(Byte value) {
            addCriterion("hostpital =", value, "hostpital");
            return (Criteria) this;
        }

        public Criteria andHostpitalNotEqualTo(Byte value) {
            addCriterion("hostpital <>", value, "hostpital");
            return (Criteria) this;
        }

        public Criteria andHostpitalGreaterThan(Byte value) {
            addCriterion("hostpital >", value, "hostpital");
            return (Criteria) this;
        }

        public Criteria andHostpitalGreaterThanOrEqualTo(Byte value) {
            addCriterion("hostpital >=", value, "hostpital");
            return (Criteria) this;
        }

        public Criteria andHostpitalLessThan(Byte value) {
            addCriterion("hostpital <", value, "hostpital");
            return (Criteria) this;
        }

        public Criteria andHostpitalLessThanOrEqualTo(Byte value) {
            addCriterion("hostpital <=", value, "hostpital");
            return (Criteria) this;
        }

        public Criteria andHostpitalIn(List<Byte> values) {
            addCriterion("hostpital in", values, "hostpital");
            return (Criteria) this;
        }

        public Criteria andHostpitalNotIn(List<Byte> values) {
            addCriterion("hostpital not in", values, "hostpital");
            return (Criteria) this;
        }

        public Criteria andHostpitalBetween(Byte value1, Byte value2) {
            addCriterion("hostpital between", value1, value2, "hostpital");
            return (Criteria) this;
        }

        public Criteria andHostpitalNotBetween(Byte value1, Byte value2) {
            addCriterion("hostpital not between", value1, value2, "hostpital");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 21 21:38:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table minidoctor_arrangement
     *
     * @mbggenerated Fri Dec 21 21:38:21 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}