package com.can.minidoctor.core.entity;

import java.io.Serializable;
import java.util.Date;

public class MinidoctorDatement implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.id
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.arrange_id
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private Long arrangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.work_date
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private Date workDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.time_section
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private String timeSection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.open_id
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.name
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.identification
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private String identification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.mobile
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.enabled
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private Byte enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.hostpital
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private Byte hostpital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.create_time
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minidoctor_datement.update_time
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table minidoctor_datement
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.id
     *
     * @return the value of minidoctor_datement.id
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.id
     *
     * @param id the value for minidoctor_datement.id
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.arrange_id
     *
     * @return the value of minidoctor_datement.arrange_id
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public Long getArrangeId() {
        return arrangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.arrange_id
     *
     * @param arrangeId the value for minidoctor_datement.arrange_id
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setArrangeId(Long arrangeId) {
        this.arrangeId = arrangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.work_date
     *
     * @return the value of minidoctor_datement.work_date
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public Date getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.work_date
     *
     * @param workDate the value for minidoctor_datement.work_date
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setWorkDate(Date workDate) {
        this.workDate = workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.time_section
     *
     * @return the value of minidoctor_datement.time_section
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public String getTimeSection() {
        return timeSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.time_section
     *
     * @param timeSection the value for minidoctor_datement.time_section
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setTimeSection(String timeSection) {
        this.timeSection = timeSection == null ? null : timeSection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.open_id
     *
     * @return the value of minidoctor_datement.open_id
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.open_id
     *
     * @param openId the value for minidoctor_datement.open_id
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.name
     *
     * @return the value of minidoctor_datement.name
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.name
     *
     * @param name the value for minidoctor_datement.name
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.identification
     *
     * @return the value of minidoctor_datement.identification
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public String getIdentification() {
        return identification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.identification
     *
     * @param identification the value for minidoctor_datement.identification
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setIdentification(String identification) {
        this.identification = identification == null ? null : identification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.mobile
     *
     * @return the value of minidoctor_datement.mobile
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.mobile
     *
     * @param mobile the value for minidoctor_datement.mobile
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.enabled
     *
     * @return the value of minidoctor_datement.enabled
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.enabled
     *
     * @param enabled the value for minidoctor_datement.enabled
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.hostpital
     *
     * @return the value of minidoctor_datement.hostpital
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public Byte getHostpital() {
        return hostpital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.hostpital
     *
     * @param hostpital the value for minidoctor_datement.hostpital
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setHostpital(Byte hostpital) {
        this.hostpital = hostpital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.create_time
     *
     * @return the value of minidoctor_datement.create_time
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.create_time
     *
     * @param createTime the value for minidoctor_datement.create_time
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minidoctor_datement.update_time
     *
     * @return the value of minidoctor_datement.update_time
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minidoctor_datement.update_time
     *
     * @param updateTime the value for minidoctor_datement.update_time
     *
     * @mbggenerated Sat Dec 22 12:05:56 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}